# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'fflint Action'
description: 'GitHub Action for fflint, a linter for file formats'
author: 'fileformat'
branding:
  color: 'grey-dark'
  icon: 'file-text'

inputs:
  args:
    description: 'Options to pass to fflint'
    required: false
  command:
    description: 'Command to run'
    default: 'ext'
    required: false
  files:
    description: 'Files to checks'
    default: '**/*'
    required: false
  version:
    description: 'fflint version to use'
    default: 'latest'
    required: false

outputs:
  artifacts:
    description: 'Build result artifacts'

runs:
  using: 'node20'
  main: 'dist/index.js'
